#docker build -t webis/query-spelling-correction:0.0.1-dev -f Dockerfile.dev .
FROM ubuntu:22.04

# Install dependencies
RUN apt-get update \
	&& apt-get upgrade -y \
	&& apt-get install -y python3 python3-pip python-is-python3 openjdk-11-jdk wget \
	build-essential hunspell-en-us libhunspell-dev python3-dev \
	&& pip3 install jupyter ir_datasets tira>=0.0.89 \
	hunspell pyspellchecker \
	&& rm -Rf /var/cache/apt \
	&& rm -Rf /root/.cache/pip

